name: GHActions

on: push

jobs:
  
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  
  dependency:
    needs: [macos, windows]
    runs-on: macos-latest
    steps:
    - run: date
